### ISSUE TITLE
What license is this released as?

### ISSUE THREAD

**Issue by julianrendell** [vvisvanathan/TRON#5]
Very cool!

Would love to know under what terms I can use it in classes and, possibly for inclusion in a Tron inspired event; I'm thinking hosting it on a hidden ESP8266 or similar WiFi AP. 

Thanks in advance!

**Comment by vvisvanathan** [comment]
Hey @julianrendell , thanks for reaching out and for your interest in my old bootcamp project! I'm thrilled that this work can be useful to someone. I added an MIT license to the repo, hopefully that suits your needs

**Comment by julianrendell** [comment]
Perfect- thank you!

If everything works out I’ll try and add a photo or links to the project.
